### PR TITLE
[android] adding material theme to BuyActivity.

### PR DESCRIPTION
**Pull request by marcelinkaaa**
Don't want to change any styles yet. Just wanted to extend AbstractActivity2 and set up a new toolbar. Let me know if its ok. 
Removed toolbar when in InterstitialMode.

### CODE REVIEW

**Comment by aldenml** [comment]
In principle I don't see nothing wrong, but maybe the override of `onCreate` can be removed.

**Comment by aldenml** [comment]
does this toolbar pick the random pitch in the title?

**Comment by marcelinkaaa** [comment]
Hmmm I thought it only did so when in interstitial mode. Just came back will check in a bit.

**Comment by aldenml** [comment]
much better, any visual change in L&F? screenshot?

**Comment by marcelinkaaa** [comment]
No visual changes in layout or function... Just adding toolbar. The title together with a random pitch is shown in settings -> remove ads as well as in interstitial version. 

screenshot_20161209-141355
screenshot_20161209-141918

**Pull request merged**
