### PR TITLE
[android] issue #116 repositioning songs in playlist

### PR DESCRIPTION
**Pull request by grzesiekrzaca**
Everything was "ok" in the View. The problem lay with no listener that would change the adapter (and data in system). The problem with the adapter is that it uses a copy of the data other than the one in ArryAdaper (why? 0.o) so that copy also has to be updated.

### CODE REVIEW

**Comment by gubatron** [comment]
just saw this, will test and review your branch. Thank you for submitting this.

**Comment by gubatron** [comment]
note: next time please submit your pull request on a separate branch.

**Comment by gubatron** [comment]
awesome, it works.
@aldenml this LGTM, please take a look before we merge.

In the meantime @grzesiekrzaca please send me your bitcoin payment address to send you the bounty payment to gubatron@gmail.com

Then let's try another ticket to see how you work with more complex/larger problems.
So far 👍 👍

**Comment by aldenml** [comment]
Hi @grzesiekrzaca, this part of the code is not the one I'm most familiar with but it LGTM. One question though: Why the `mDataListLock` and the `synchronized` blocks?

**Comment by grzesiekrzaca** [comment]
So that any concurrency problems don't arise from the fact that there are multiple resources that represent the same thing in this class (due to inheritance from ArrayAdaper). Though I see I made a mistake and got that super call outside of critical section. (Which is also not perfect as in this case we notify observers of the list inside a critical section, though in normal application this should not be a problem).
PR to fix this (update pr from a new branch - i hope this is it): #139
Also sorry for VC mess. I'm used to bitbucket and feature branches setup.

**Pull request merged**
