### PR TITLE
[android] Make control notification visible

### PR DESCRIPTION
**Pull request by grzesiekrzaca**
#252 
This will allow the notification contents to be visible on lock screen when notification privacy is up. On my phone (S5 6.0.1) at least this has a side effect of the fact that the notification in notification area is now expanding (previously lots of ongoing notifications blocked that expansion)
so it affects #251

### CODE REVIEW

**Comment by aldenml** [comment]
This is API 21.

As a general note (for all of us), this is precisely the reason I didn't want to up the SDK api. I suppose you get some warnings in the build process, or not?

**Comment by grzesiekrzaca** [comment]
AFAIK Pre 21 devices will not show the notification on the lock screen, and this will not have an effect on the normal notification (at least that how NotificationCompat.Builder should work)
I don't have an old device at the moment i'll check on an emulator.
Or do you just want an if(Build.VERSION.SDK_INT >= ) to be extra safe?

**Comment by grzesiekrzaca** [comment]
Tested on emulator API 19, no issues.

**Comment by aldenml** [comment]
I rather no access/touch any API beyond 16. Is this the only solution to the issue?

**Comment by grzesiekrzaca** [comment]
No, that's "new" functionality. 
They messed around with allowing custom stuff on the lock screen between 4.1 (or close enough) and 5.0 (API 21) when they removed it and moved the interaction with apps to notifications. So they introduced various levels of visibility (public (show all),private (show notification but protect content),secret (don't show the notification)) to accommodate that.

**Comment by aldenml** [comment]
Shall we use `NotificationCompat.Builder` instead?

**Comment by grzesiekrzaca** [comment]
I don't understand. We use NotificationCompat.Builder

**Comment by aldenml** [comment]
right, then you should put a private constant with the value `Notification.VISIBILITY_PUBLIC` and use that instead

**Pull request merged**
