### PR TITLE
[desktop] Add MagnetDL torrent icon

### PR DESCRIPTION
**Pull request by Aholicknight**
This adds the MagnetDL torrent icon to FrostWire. I found a similar logo online, which is free to use. I once again grayscaled the icon and resized the image to 20x20.

### CODE REVIEW

**Comment by gubatron** [comment]
Thank you so much for this submission @Aholicknight 
In order to merge I'll need you to do a few of things:

1. We need it in 16x16.
2. We need the source icons to be in this RGB color: `#8ea2b4`
3. Please rename the file to be `magnetdl_source.png`
4. If you can add the code in the [source renderer](https://github.com/frostwire/frostwire/blob/master/desktop/src/com/limegroup/gnutella/gui/search/SourceRenderer.java#L49) it'd be awesome so that your pull request is 100% complete, the lines there should give you an idea.

Screen Shot 2020-11-16 at 12 09 07 PM

**Comment by Aholicknight** [comment]
I will correct those changes soon.

**Comment by Aholicknight** [comment]
Fixed.

**Comment by Aholicknight** [comment]
Why did the build fail @gubatron ?

**Comment by gubatron** [comment]
Next time I'll do a squash and merge, first to not pollude the git history, but secondly because Travis can abort the build if there are too many jobs running.

I fixed some headers and the build was passing
Screen Shot 2020-11-17 at 2 29 06 PM

You can always click and see what went wrong with the travis build.

**Comment by gubatron** [comment]
Squashing and merging, let's see if the build will pass.

**Comment by gubatron** [comment]
Indeed: https://travis-ci.org/github/frostwire/frostwire/jobs/744280154

Screen Shot 2020-11-17 at 2 36 22 PM

Everything good!
Thanks, please keep those PRs coming, we can use the help

**Comment by gubatron** [comment]
oh actually, looks like you broke it :p

```
:compileJava<-------------> 0% EXECUTING [20s]> :compileJava> Task :compileJava
/home/travis/build/frostwire/frostwire/desktop/src/com/limegroup/gnutella/gui/search/SourceRenderer.java:50: error: cannot find symbol
            sourceIcons.put("magnetdl", GuiMediator.getThemeImage("magnetdl_source"));
                                        ^
  symbol:   variable GuiMediator
  location: class SourceRenderer
```

It's not `GuiMediator`, it's `GUIMediator`

I got it.

**Pull request merged**
