### PR TITLE
Android permanent notification deamon

### PR DESCRIPTION
**Pull request by grzesiekrzaca**

### CODE REVIEW

**Comment by gubatron** [comment]
@grzesiekrzaca can you join us on slack? I'd like to help you with git and rebasing, to see if it's possible to clean my commit from this branch

http://frostwire.com/chat

**Comment by gubatron** [comment]
when you join the Slack chat, go to the #hacking-android chatroom and type "@gubatron" so I know you're there.

Also paste the output of:

```
git remote -v
```

To see how you have set up your remotes, and we'll take it from there.

**Comment by gubatron** [comment]
The idea is that your remote repos should look something like this:

```
$ git remote -v
origin	git@github.com:frostwire/frostwire.git (push)
origin	git@github.com:frostwire/frostwire.git (fetch)
grzesiekrzaca	https://github.com/grzesiekrzaca/frostwire (push)
grzesiekrzaca	https://github.com/grzesiekrzaca/frostwire (fetch)
gubatron	git@github.com:gubatron/frostwire (push)
gubatron	git@github.com:gubatron/frostwire (fetch)
```

By internal convention, we call the original repository at https://github.com/frostwire/frostwire -> `origin` and we call our own forks by our username.

**Comment by aldenml** [comment]
Ok, I hope you don't mind this is a process. What do you think about moving this out from `MainActivity` to `EngineServices`, and explore if the class `NotificationUpdateDemon` is necessary or not?

**Pull request closed without merging**
