### PR TITLE
Adding androidTest with Espresso tests

### PR DESCRIPTION
**Pull request by muckachina**
Here some successful tests to Search files and Download files filtered by source.

I'll keep working on Download files filtering by Source so I can have all tests of sources with espresso.

### CODE REVIEW

**Comment by gubatron** [comment]
thanks_dalai_lama

Thank you Thank you Thank you!

Let's talk tomorrow so you tell me how to take these for a spin, I'd like to see if we can try these on the google play dashboard so we can run these tests on lots of devices.

Great way to end the day seeing this, you rock @muckachina !

**Comment by gubatron** [comment]
Please do this for me:

```
git checkout -b espresso-october-2016
git push https://github.com/muckachina/frostwire espresso-october-2016
```

and let me know when that branch is up on your repo, so I can fetch that branch as I don't want to merge this into master yet (you were working on your master)

**Comment by muckachina** [comment]
Oki Done, I already created espresso-october-2016 branch and everything is pushed there.

I'll be working on my muckachina/frostwire repo and pushing all new changes to this espresso branch... please let me know if I have to 'pull request' from that branch 'espresso-october-2016' so you can add the changes or you can pull by your own, I'm not so good with git commands, I'm working with VCS on Android Studio.

The only changes you will see compared to your master is the **'androidTest'** folder that contains all the test and few **espresso dependencies added on build.gradle**.

Also let me know if you already have a Google Play Dashboard to check the option for multiple devices, I think is oriented to multiple APKs testing but it is useful too since we already have 4 different scenarios (Basic and Plus with and without Plan purchased).

**Comment by gubatron** [comment]
Thank you.

To answer your question, I'll close this pull request, and now just open a new pull request from that branch. You can send the PR right from your github.com account (on the site), no need for cmd line to do that, I actually never send PRs from the command line, I don't even know how to.

I believe I do have it checked for multiple devices on something called "Pre-Launch Report", not sure if this is the espresso stuff, but look, it seems we ran some tests in the past, not sure if this was done automatically by google or if we had a test written by you back then.

screen shot 2016-10-11 at 9 42 31 am

**Pull request closed without merging**
