### PR TITLE
Updated polish translation

### PR DESCRIPTION
**Pull request by ireun**

### CODE REVIEW

**Comment by gubatron** [comment]
@kad3mlia please review and let us know if this is good to be merged.

**Comment by gubatron** [comment]
thank you @ireun !

**Comment by gubatron** [comment]
@marcelinkaaa can you take a look at the polish translation changes and tell us if this is good to be merged?

**Comment by gubatron** [comment]
Thank you so much for your translation @ireun 
putin_goodjob

**Comment by gubatron** [comment]
(I know how Polish people must hate him, LOL, just messing with you @ireun )

**Comment by ireun** [comment]
Hahahha, no problem :D

**Pull request merged**
