### PR TITLE
[android] added tabLayout, removed TitlePageIndicator

### PR DESCRIPTION
**Pull request by marcelinkaaa**

### CODE REVIEW

**Comment by aldenml** [comment]
well, `TabLayout` is 100% new for me, looking at it

**Comment by gubatron** [comment]
it's all in @marcelinkaaa googling powers.
Before this we had replaced it with `PagerTitleStrip` but it sucked.

**Comment by aldenml** [comment]
nice, I prefer the animation (with color fading) from apollo, but I guess you are all ok with how it works now. If you think UX is ok, I'm fine with it. I also see that you just fixed the compilation issue.

LGTM

**Comment by aldenml** [comment]
@marcelinkaaa :clap:

**Comment by marcelinkaaa** [comment]
I'm fine with the current animation, and like to have an option of horizontal scroll to get to the last tab faster. It's also so much easier to change and maintain, at least for me. :)

**Comment by aldenml** [comment]
I don't want to merge at this moment because I don't know if @gubatron is working on it (last minute change)

**Comment by marcelinkaaa** [comment]
No merging yet, we are trying to see if we can more easily apply tablayout in transfers, browse, etc.

**Comment by gubatron** [comment]
yeah don't merge, there's more work coming with this TabLayout stuff, already got the selection styles working and some of the interaction on Search
screen shot 2017-05-08 at 9 55 28 pm
.

I believe quite a lot of code will be gone once this is functionally on par with the uber customized radiogroup, my guess is that the UI will be a lot faster too, a lot less code happening

**Comment by gubatron** [comment]
@marcelinkaaa functionality has been plugged, once you've gotten down how to make icons look correctly (hopefully with just styles, if not we'll have to play with the "intrinsic" bounds and what not programatically), then I'll do the same for My Files, and once that's done, it's going to be major cleanup time.

I've just put the code side by side for now.

**Comment by aldenml** [comment]
just asking, what's the status of this?

**Comment by marcelinkaaa** [comment]
@aldenml  Angel is out for now, and I will need help with connecting the tabs to the corresponding views and creating a custom tab view for horizontal search tabs. 
I am finishing redoing the icons - need to adjust sizes, etc. The old ones can be deleted after that.

**Comment by gubatron** [comment]
I'll start connecting this over the weekend, I'm almost done with Image Fragment viewer, FrostWire is going to look and feel kick ass.

**Comment by gubatron** [comment]
just rebased this branch with master without pulling the latest changes.
@marcelinkaaa please do not pull this branch, instead push force whatever you have on your computer.

**Comment by marcelinkaaa** [comment]
@gubatron done.

**Comment by gubatron** [comment]
yay, thanks!

**Comment by gubatron** [comment]
closing this, renaming branch to `tablayout-refactor`

**Pull request closed without merging**
