### PR TITLE
Feature/granular/torrent preferences

### PR DESCRIPTION
**Pull request by grzesiekrzaca**
Part of the granular merging of settings makeover changes. This relates to numerical properties in torrent preferences.

### CODE REVIEW

**Comment by aldenml** [comment]
I think it's a lot better if you use the android framework for plurals

**Comment by grzesiekrzaca** [comment]
I'll change that

**Comment by gubatron** [comment]
sent you a tidying pull request to your repo @grzesiekrzaca, cheers.

**Comment by grzesiekrzaca** [comment]
Can we start merging some of those PRs? There will probably be conflicts in `SettingsActivity2` (imports)

**Comment by aldenml** [comment]
Sorry for the delay, I have limited access for a few days

**Comment by gubatron** [comment]
dude @aldenml enjoy your free time!

**Pull request merged**
