### PR TITLE
[android] copy other preferences

### PR DESCRIPTION
**Pull request by grzesiekrzaca**
This is a copy of existing code with the exception of the comment about UXStats. I think that that should be tackled in another PR as it would touch update logic.

### CODE REVIEW

**Comment by aldenml** [comment]
Why so many things imports?

**Comment by grzesiekrzaca** [comment]
Forgot to `Ctrl+Alt+O` after cherry picking WIP branch commits

**Comment by gubatron** [comment]
@aldenml when you come back, let's make it a priority helping @grzesiekrzaca get all the Settings work  finished and merged for a release. Still a lot of work to be done after this on My Files (Material Design, New Push and Hold Selection Modes, and grid display of images and videos), of course always adhering to your good standards.

Also let's make sure once this happens, that we don't have a single "SomeClass2" in the code base, that everything is finally replaced.

I'll be at CES until sunday, I'll try to connect and work for half of the day.

**Comment by aldenml** [comment]
I took over this because `R.layout.view_preference_button_action` wasn't the correct layout to use and there was a good opportunity to simplify `ButtonActionPreference2`. See https://github.com/frostwire/frostwire/commit/edaa55cac73e1a25b4b7d67064db3815f41c1d9d

Feel free to close this PR.

**Pull request closed without merging**
