### PR TITLE
Night theme rebased by gubatron

### PR DESCRIPTION
**Pull request by gubatron**
Continuation from [Pull 109](https://github.com/frostwire/frostwire/pull/1019) by @marcelinkaaa (A million thanks for this work, it's one of the most requested features I couldn't ever deliver)

image

image

image

image

image

"Mostly tested on API 33. On API 28 the app would crash sometimes on the music player citing something about an ad size - it should not be related to this branch.

I added night theme colors. Updated tint of icons, color of text, and backgrounds. Updated custom styles for toolbars, etc.
I also added a UI for added Dark Theme in preferences, but at this point, I don't think I can make it work on my own. Maybe you could add it to preferences. For now it works if a user changes to Dark Theme from phone settings. Let me know what you think, and if you want it." -@marcelinkaaa

Let's hope I can replicate those crashes now

### CODE REVIEW

**Comment by gubatron** [comment]
This pull request pertains to this bounty issue (priced at $250)
https://github.com/frostwire/frostwire/issues/908

**Comment by gubatron** [comment]
Runs great!
Now I suppose I'll figure out how to make it turn on/off the current theme on the settings switch button

**Comment by marcelinkaaa** [comment]
Hope its easier than it looked for me :) I forgot how big of an application FrostWire was :) it took a longer time than I thought but it was very fun working on another platform after learning SwiftUI.

**Comment by gubatron** [comment]
SwiftUI!!! nice, it's on my list of toys to play with, but recently I discovered Flutter to make cross OS apps, learning a ton on that front.

**Comment by gubatron** [comment]
@marcelinkaaa I need your help figuring out how to change the theme programatically.

I only see one folder that hints me how this is working: "values-night" vs "values"
Screenshot 2024-10-09 at 10 39 33 AM

After going through the pull request I refactored all the calls to get the tint to `UIUtils.getAppIconPrimaryColor`
```java
public static int getAppIconPrimaryColor(Context context) {
        return ContextCompat.getColor(context, R.color.app_icon_primary);
}
```

I noticed how every component had that call and moved it to a single place. I wonder if changing the theme is somehow related to that `R.color.app_icon_primary`, or if there's a way to tell the app to use `valued-night` color values in a programmatic form.

I wonder how now the app is hardcoded to use the dark values, is that in one of the XML files?

**Comment by gubatron** [comment]
Screenshot 2024-10-09 at 10 47 49 AM

is it maybe just a matter of swaping the "parent" theme of `Theme.FrostWire` between `Theme.AppCompat.DayNight.NoActionBar` and `Theme.AppCompat.Light.NoActionBar`?

I notice this has been hardcoded in `android/res/values/themes.xml`

**Comment by marcelinkaaa** [comment]
Hi there, 
So yes "values-night" vs "values" is all that was needed. The color names are the same and values change depending on the theme selected. 
From what I was reading adding the change in settings seemed straightforward but there is so much code in this app I always run into some errors. 

From my understanding, the whole app needs to use a theme that supports both light and dark modes, such as Theme.AppCompat.DayNight.NoActionBar - which we now have. Then AppCompatDelegate.setDefaultNightMode() is used to switch between night and light modes, this recreates the activity which might affect the current state - and I was not sure how to deal with that. 

I was thinking about doing it with switch mode similar to this:

switch (themePreference) {
                case "light":
                    AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);
                    break;
                case "dark":
                    AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);
                    break;
                case "system_default":
                default:
                    AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM);
                    break;
            }

**Comment by gubatron** [comment]
Thank you, will checkout `AppCompatDelegate.setDefaultNightMode(MODE)`, this greatly simplifies what I was thinking of doing which was exactly that, to either let the user turn it on or off, or to follow whatever system preferences they have.

I just have to create a 3-way preference that maps your switch logic.

Thank you!

**Comment by marcelinkaaa** [comment]
Great. It was fun revisiting an old project! Glad the settings work!

**Pull request merged**
