### PR TITLE
Espresso-october-2016 Branch

### PR DESCRIPTION
**Pull request by muckachina**
Espresso tests includes SearchTest (check if getting results from all categories) and DownloadTest to download a file from a specific source.

### CODE REVIEW

**Comment by gubatron** [comment]
Thank you very much!

I'll now see if I can rebase this branch and bring it up to speed.

Is there a gradle task I must run in order to start the automatic tests? maybe something like

`./gradlew espresso` ?

no clue how to use it

**Comment by muckachina** [comment]
This is how I do on Android Studio:

- **On Project Files select androidTest/java > com/frostwire/android > gui/activities and right click to run for example on 'DownloadTest'** This test go to Settings, un-select all sources except Archive.org, go back to search, search 'Creative Commons' and download the first result on Audio for Archive.org

**Comment by gubatron** [comment]
awesome, I'll do that!

**Comment by gubatron** [comment]
@muckachina I've rebased this branch, and created a clone branch called `espresso-november-2016` on my repository.

When you have a chance, add my repository as a remote (if you don't have it already):

```
git remote add gubatron https://github.com/gubatron/frostwire
```

then do a `git fetch gubatron`

and you should get all my branches, then you can delete your local `espresso-october-2016` branch and push the `espresso-november-2016` branch to your github repo.

I'll be closing this and opening a new pull request.

**Pull request closed without merging**
