### PR TITLE
[android] Solving equalizer doesn't appear in player activity

### PR DESCRIPTION
**Pull request by votaguz**
Issue #357 : 
Just changed the call from ```startActivity``` to ```startActivityForResult``` method. 

The only guess that i have about this issue, it seems to be related to the integer value passed as expected value internally to ```startActivityForResult```.

I checked android ```Activity``` class, found ```startActivity``` calls ```startActivityForResult``` passing a ```-1``` as expected result but if that value is changed by ```0``` (I think we can use any integer) equalizer is showed with no problems

````
    /**
     * Launch a new activity.  You will not receive any information about when
     * the activity exits.  This implementation overrides the base version,
     * providing information about
     * the activity performing the launch.  Because of this additional
     * information, the {@link Intent#FLAG_ACTIVITY_NEW_TASK} launch flag is not
     * required; if not specified, the new activity will be added to the
     * task of the caller.
     *
     * <p>This method throws {@link android.content.ActivityNotFoundException}
     * if there was no Activity found to run the given Intent.
     *
     * @param intent The intent to start.
     * @param options Additional options for how the Activity should be started.
     * See {@link android.content.Context#startActivity(Intent, Bundle)
     * Context.startActivity(Intent, Bundle)} for more details.
     *
     * @throws android.content.ActivityNotFoundException
     *
     * @see #startActivity(Intent)
     * @see #startActivityForResult
     */
    @Override
    public void startActivity(Intent intent, @Nullable Bundle options) {
        if (options != null) {
            startActivityForResult(intent, -1, options);
        } else {
            // Note we want to go through this call for compatibility with
            // applications that may have overridden the method.
            startActivityForResult(intent, -1);
        }
    }
````

58afc8be4a2fa449978163

### CODE REVIEW

**Comment by aldenml** [comment]
This is good, it's documented in https://developer.android.com/reference/android/media/audiofx/AudioEffect.html#ACTION_DISPLAY_AUDIO_EFFECT_CONTROL_PANEL

> The calling application must use the **startActivityForResult(Intent, int)** method to launch the control panel so that its package name is indicated and used by the control panel application to keep track of changes for this particular application.

**Comment by gubatron** [comment]
shaquille-o-neal

way to go @votaguz !!!

I think @muckachina will be happy to see this ancient issue finally resolved.

**Comment by muckachina** [comment]
Thank you! Issue closed on FW public repo and QA :)

Tested with internal equalizer on Android 4.2 and external equalizer apps on Android 5 and 6... although no all Equalizers are recognized by FW but it seems because they also act like Players (for example 'Music Equalizer' which is a popular one)

**Comment by gubatron** [comment]
kvh2fyopyztshq_rpwiuwnwneuvavxd-ccjr46o0ebe
"Yeah!"

**Pull request merged**
