### PR TITLE
Browsing through code, cleaned up some sonarqube warnings. 

### PR DESCRIPTION
**Pull request by alvonellos**
Hey Guys, 

  I've never contributed before, but I always wanted to get under the hood of Frostwire and browse through the code. I noticed a few warnings while I was browsing, and thought I would fix them. Hope this helps. 

- Alex

### CODE REVIEW

**Comment by gubatron** [comment]
sorry I didn't see your pull request until now.

**Comment by alvonellos** [comment]
It’s all good. Go ahead and merge? It builds okay.

Sent from my iPhone

On Jan 6, 2023, at 18:43, Angel Leon ***@***.***> wrote:

﻿

sorry I didn't see your pull request until now.

**Comment by gubatron** [comment]
yeah, but it needs to run and not break. If you don't want to fix, maybe I'll just clone your branch and selectively merge some of the fixes.

Not a big fan of merging big PRs and then introduce bugs

**Comment by gubatron** [comment]
Can you clone these changes to another branch and submit another PR from that branch please?
Screenshot 2023-01-07 at 6 40 58 AM

This way I can experiment without screwing things up on master

**Comment by gubatron** [comment]
fetched your master and testing it.
it breaks music playback, let's see if I can fix it because there are several things I'd like to merge.

**Comment by gubatron** [comment]
Screenshot 2023-01-08 at 12 58 20 PM

LOL, no shit it won't playback nor download torrents if I merge this.

Sorry. Not merging this.

Please submit smaller patches and don't delete our binaries from the repo.

**Pull request closed without merging**
