### PR TITLE
[android] updated notification frostwire icon

### PR DESCRIPTION
**Pull request by marcelinkaaa**
So the reason that the FrostWire notification icon looked like a nontransparent white ball is that starting in Android Lollipop all the icons in status bar are required to be white (although at times apps will hack this to use their colored version). And we were using our colored version without any modifications so that android was paining it white. 

I think Alden did that on purpose as it was causing some problems on lollipop, however now everything seems to be working fine after the recent updates to android app. Tested it on lollipop, marshmallow and api 16 emulator.

### CODE REVIEW

**Comment by gubatron** [comment]
wohoo, so cool to see this being taken off my hands.

I'm going to test this branch on 4.4. and 5.0 and see what happens.

**Comment by marcelinkaaa** [comment]
awesome, thank you.

**Comment by gubatron** [comment]
perfect on Lollypop

**Comment by gubatron** [comment]
perfect on 4.4

**Comment by gubatron** [comment]
Kitkat I think it was called

**Comment by gubatron** [comment]
thanks-fist-bump

**Pull request merged**
